### ISSUE TITLE
On failed or cancelled transactions, pinpad gets reinitialized by Core POS creating loop

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/IS4C#13]
When the customer hits the red X or cancel button, or a card gets declined, Core POS will show the error code, but the pinpad gets reinitialized to take payment again. Ideally the pinpad would not be immediately reinitialized, as the method of payment may have changed (eg. the pinpad was sent $2 to process on debit before, but the customer actually has a credit card and told the cashier the wrong thing).

**Comment by thefinn93** [comment]
I'm having trouble reproducing this. I hit the X on the pin pad, the POS showed "ABORTED", and the pinpad does not get re-initialized.
