### ISSUE TITLE
We attempt to store the signature even if the user hit cancel

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/IS4C#9]

**Comment by danry25** [comment]
Verify that at least a few dozen pixels have been filled in if storing a partial signature. Otherwise, discard the signature and void the transaction.

**Comment by thefinn93** [comment]
This is a code flaw where even if the user hit's the red X on the pinpad and we don't get a signature, we store a line in the DB with a signature of `null`. The UI correctly identifies the failed signature retrieval and prompts the cashier to void the transaction or allow the user to try again (see #4 for more on that). If you'd like to check if the vector we got back actually contains anything, I encourage you to open another issue.
